"""
Django settings for cyberweb project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""


import os
from pathlib import Path
import django_heroku
import pyrebase
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^jm2+mtocft_#l)#uw32$9(im(b4%h&%o@i4_ugic*egq$6gua'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG=True
# DEBUG = False 

ALLOWED_HOSTS = ['*']


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'webapp',
    # 'pyrebase',
    # external package
    # 'Pillow',

    # internal package

]



config = {
    "apiKey": "AIzaSyDFNY2e6KDTN_0V3e55R24SnSa5VoO58B4",
    "authDomain": "officialwebsite-be636.firebaseapp.com",
    "projectId": "officialwebsite-be636",
    "storageBucket": "officialwebsite-be636.appspot.com",
    "messagingSenderId": "158902502920",
    "appId": "1:158902502920:web:782a23ef0fa74ef28873bd",
    "measurementId": "G-1KRY6VCQB0",
    "databaseURL":""
}
firebase=pyrebase.initialize_app(config)
storage=firebase.storage()


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cyberweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cyberweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'd7i3iujjo26ac6',
        'USER': 'savypfudnfloje',
        'PASSWORD': '2d765c997589d71c0d9fa34e19fe7fd17d9d017b9ff1b552912d43495a7ac661',
        'HOST': 'ec2-44-206-137-96.compute-1.amazonaws.com',
        'PORT': 5432,
    }

    # 'default': {

    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'd7i3iujjo26ac6',
    #     'USER': 'savypfudnfloje',
    #     'PASSWORD': '2d765c997589d71c0d9fa34e19fe7fd17d9d017b9ff1b552912d43495a7ac661',
    #     'HOST': 'ec2-44-206-137-96.compute-1.amazonaws.com',
    #     'PORT': 5432,
    # }
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }

    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'postgres',
    #     'USER': 'yugal',
    #     'PASSWORD': 'pythojs',
    #     'HOST': 'localhost',
    #     'PORT': 5432,
    }
db_from_env = dj_database_url.config(conn_max_age=600)
DATABASES['default'].update(db_from_env)
# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


# for development
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static/")
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# for production
# STATIC_ROOT=os.path.join(BASE_DIR,"static")

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
django_heroku.settings(locals())
