# Generated by Django 4.1 on 2022-08-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
