# Generated by Django 4.1 on 2022-08-07 13:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_career_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('sub_title', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(default='', max_length=10000)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='career',
            name='vacancy_title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='SubServices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(default='', max_length=10000)),
                ('image', models.ImageField(upload_to='images/')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.services')),
            ],
        ),
    ]
