# Generated by Django 4.1 on 2022-08-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_services_alter_career_vacancy_title_subservices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subservices',
            old_name='service_id',
            new_name='service',
        ),
    ]
