# Generated by Django 4.1 on 2022-08-07 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('link', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=10000)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
