# Generated by Django 4.1 on 2022-08-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.CharField(default='', max_length=10001),
        ),
    ]
