# Generated by Django 4.1 on 2022-08-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='education_status',
            field=models.CharField(choices=[('SEE', 'SEE'), ('Highschool', 'Highschool'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters')], max_length=20),
        ),
    ]
