# Generated by Django 4.1 on 2022-08-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_jobapplication_education_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='education_status',
            field=models.CharField(choices=[('SEE', 'SEE'), ('+2', '+2'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters')], max_length=20),
        ),
    ]
