# Generated by Django 4.1 on 2022-08-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_jobapplication_education_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cv_pdf',
            field=models.FileField(default='/media/images/noice.jpg', upload_to='files/'),
        ),
    ]
