# Generated by Django 4.1 on 2022-08-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_jobapplication_cv_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], default='Full-Time', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='education_status',
            field=models.CharField(choices=[('SEE', 'SEE'), ('+2', '+2'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Phd', 'Phd')], default='SEE', max_length=20),
        ),
    ]
