# Generated by Django 4.1 on 2022-08-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_jobapplication_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cv_pdf',
            field=models.FileField(default='/media/images/noice.jpg', upload_to='files'),
        ),
    ]
