# Generated by Django 4.1 on 2022-08-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_alter_jobapplication_cv_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='cv_pdf',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cv_link',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
