# Generated by Django 4.1 on 2022-08-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_remove_jobapplication_cv_pdf_jobapplication_cv_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cv_link',
            field=models.CharField(default='', editable=False, max_length=10000),
        ),
    ]
