# Generated by Django 4.1 on 2022-08-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='cv_link',
            field=models.CharField(default='', editable=False, max_length=10000),
        ),
    ]
