# Generated by Django 4.1 on 2022-08-10 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_teammember_cv_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='position',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='webapp.career'),
        ),
    ]
